# With Matrix we can run the same job with different configutation
# Basiclly we will run six workflow (every operation system with any node version) 

name: Matrix Demo
on: push
jobs:
    build-project:
        # We want to continue running the matrix even if some combination leed to fail 
        continue-on-error: true 
        strategy:
            matrix:
                # Here we can set any key we want and use it everywhere in a level job
                node-version: [12, 14, 16]
                operation-system: [ubuntu-latest, windows-lates]
                # Alternative, we can use specific combination like we want
                include:
                    - node-version: 16
                      operation-system: windows-latest
        runs-on: ${{ matrix.operation-system }}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build